/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * # Errors
         *     Returns safe authentication, organizer permission, or storage errors.
         */
        get: operations["list"];
        put?: never;
        /**
         * # Errors
         *     Returns safe authentication, input, organizer permission, or storage errors.
         */
        post: operations["invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * # Errors
         *     Returns safe authentication, input, last-organizer, permission, or storage errors.
         */
        patch: operations["status"];
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * # Errors
         *     Requires current organizer permissions to read safe audit summaries.
         */
        get: operations["audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * # Errors
         *     Returns safe session, CSRF, or infrastructure errors.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * # Errors
         *     Returns safe input, origin, rate limit, or infrastructure errors.
         */
        post: operations["request_code"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * # Errors
         *     Returns safe session or infrastructure errors.
         */
        get: operations["session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * # Errors
         *     Returns safe input, origin, code, or infrastructure errors.
         */
        post: operations["verify_code"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * # Errors
         *     Returns authentication or safe query/persistence errors. Only organizers can read failed deliveries for others.
         */
        get: operations["inbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/teams/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * # Errors
         *     Returns NotFound for invalid/rotated links, or safe storage errors. No internal fields are projected.
         */
        get: operations["readPublicCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * # Errors
         *     Returns authentication, storage, or safe decoding errors.
         */
        get: operations["readSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * # Errors
         *     Requires current permissions, CSRF, an idempotency key and validated action data.
         */
        post: operations["mutate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * # Errors
         *     Requires organizer permissions; validates template/closure data without saving it.
         */
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendars/{token}.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * # Errors
         *     Returns NotFound for invalid/rotated links, or safe calendar/storage errors.
         */
        get: operations["feed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountResponse: {
            email: string;
            enabled: boolean;
            organizer: boolean;
            /** Format: int64 */
            user_id: number;
        };
        ActionBody: {
            id: string;
            /** @enum {string} */
            operation: "mark_notice_read";
        } | {
            id: string;
            /** @enum {string} */
            operation: "retry_email";
        } | {
            hours: components["schemas"]["HoursBody"][];
            name: string;
            /** @enum {string} */
            operation: "configure_gym";
            split: boolean;
            timezone: string;
            /** Format: int64 */
            version: number;
        } | {
            end_date: string;
            name: string;
            /** @enum {string} */
            operation: "create_season";
            start_date: string;
        } | {
            end_date: string;
            /** Format: int64 */
            id: number;
            name: string;
            /** @enum {string} */
            operation: "edit_season";
            start_date: string;
            /** Format: int64 */
            version: number;
        } | {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            operation: "set_season_status";
            status: components["schemas"]["SeasonState"];
            /** Format: int64 */
            version: number;
        } | {
            name: string;
            /** @enum {string} */
            operation: "create_team";
            primary: string;
            /** Format: int64 */
            season: number;
        } | {
            /** Format: int64 */
            id: number;
            name: string;
            /** @enum {string} */
            operation: "edit_team";
            primary: string;
            /** Format: int64 */
            version: number;
        } | {
            email: string;
            /** @enum {string} */
            operation: "assign_assistant";
            remove: boolean;
            /** Format: int64 */
            team: number;
            /** Format: int64 */
            version: number;
        } | {
            /** @enum {string} */
            operation: "assign_team_season";
            /** Format: int64 */
            season: number;
            /** Format: int64 */
            team: number;
            /** Format: int64 */
            version: number;
        } | {
            /** @enum {string} */
            operation: "rotate_team_link";
            /** Format: int64 */
            team: number;
            /** Format: int64 */
            version: number;
        } | {
            end: string;
            end_date: string;
            /** @enum {string} */
            operation: "create_slots";
            /** Format: int64 */
            season: number;
            space: components["schemas"]["SpaceBody"];
            start: string;
            start_date: string;
            weekdays: number[];
        } | {
            date: string;
            end: string;
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            operation: "edit_slot";
            space: components["schemas"]["SpaceBody"];
            start: string;
            /** Format: int64 */
            version: number;
        } | {
            enabled: boolean;
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            operation: "set_slot_enabled";
            /** Format: int64 */
            version: number;
        } | {
            end: string;
            end_date: string;
            /** @enum {string} */
            operation: "close_gym";
            reason: string;
            space: components["schemas"]["SpaceBody"];
            start: string;
            start_date: string;
        } | {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            operation: "reopen_gym";
            /** Format: int64 */
            version: number;
        } | {
            activity: components["schemas"]["ActivityBody"];
            note: string;
            /** @enum {string} */
            operation: "submit_requests";
            reason: string;
            slots: number[];
            /** Format: int64 */
            team: number;
        } | {
            activity: components["schemas"]["ActivityBody"];
            /** Format: int64 */
            id: number;
            note: string;
            /** @enum {string} */
            operation: "edit_request";
            reason: string;
            /** Format: int64 */
            slot: number;
            /** Format: int64 */
            version: number;
        } | {
            ids: number[];
            /** @enum {string} */
            operation: "withdraw_requests";
        } | {
            decisions: components["schemas"]["DecisionBody"][];
            /** @enum {string} */
            operation: "decide_requests";
        } | {
            activity: components["schemas"]["ActivityBody"];
            note: string;
            /** @enum {string} */
            operation: "book_directly";
            slots: number[];
            /** Format: int64 */
            team: number;
        } | {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            operation: "cancel_booking";
            scope: components["schemas"]["ScopeBody"];
            /** Format: int64 */
            version: number;
        } | {
            activity: components["schemas"]["ActivityBody"];
            /** Format: int64 */
            id: number;
            note: string;
            /** @enum {string} */
            operation: "change_booking";
            reason: string;
            scope: components["schemas"]["ScopeBody"];
            slots: number[];
            /** Format: int64 */
            version: number;
        } | {
            activity: components["schemas"]["ActivityBody"];
            /** Format: int64 */
            id: number;
            note: string;
            /** @enum {string} */
            operation: "move_booking";
            /** Format: int64 */
            slot: number;
            /** Format: int64 */
            version: number;
        } | {
            /** Format: int64 */
            first: number;
            /** Format: int64 */
            first_version: number;
            /** @enum {string} */
            operation: "propose_swap";
            /** Format: int64 */
            second: number;
            /** Format: int64 */
            second_version: number;
        } | {
            accept: boolean;
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            operation: "respond_swap";
            /** Format: int64 */
            version: number;
        } | {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            operation: "withdraw_swap";
            /** Format: int64 */
            version: number;
        };
        /** @enum {string} */
        ActivityBody: "practice" | "game";
        AuditView: {
            action: string;
            /** Format: int64 */
            actor: number;
            /** Format: int64 */
            occurred_at: number;
        };
        BookingView: {
            activity: string;
            /** Format: int64 */
            id: number;
            note: string;
            series?: string | null;
            /** Format: int64 */
            slot: number;
            status: string;
            /** Format: int64 */
            team: number;
            /** Format: int64 */
            version: number;
        };
        ClosureView: {
            active: boolean;
            /** Format: int64 */
            ends_at: number;
            /** Format: int64 */
            id: number;
            reason: string;
            space: string;
            /** Format: int64 */
            starts_at: number;
            /** Format: int64 */
            version: number;
        };
        CodeResponse: {
            message: string;
            /** Format: int32 */
            resend_after_seconds: number;
        };
        DecisionBody: {
            approve: boolean;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            version: number;
        };
        ErrorResponse: {
            code: string;
            issues: components["schemas"]["FieldIssue"][];
            message: string;
            request_id: string;
        };
        FieldIssue: {
            field: string;
            message: string;
        };
        GymView: {
            hours: components["schemas"]["HoursBody"][];
            name: string;
            split: boolean;
            timezone: string;
            /** Format: int64 */
            version: number;
        };
        HealthResponse: {
            status: components["schemas"]["HealthStatus"];
        };
        /** @enum {string} */
        HealthStatus: "alive" | "ready";
        HoursBody: {
            end: string;
            start: string;
            /** Format: int32 */
            weekday: number;
        };
        /** @enum {string} */
        InvitationRole: "organizer" | "coach";
        InviteBody: {
            email: string;
            role: components["schemas"]["InvitationRole"];
        };
        NoticeView: {
            /** Format: int64 */
            created_at: number;
            delivery: string;
            id: string;
            read: boolean;
            recipient: string;
            subject: string;
            text: string;
            /** Format: int64 */
            user_id: number;
        };
        OutcomeView: {
            resources: components["schemas"]["ResourceView"][];
            warnings: string[];
        };
        PreviewItem: {
            date: string;
            end?: string | null;
            error?: components["schemas"]["ErrorResponse"] | null;
            space?: string | null;
            start?: string | null;
        };
        PreviewView: {
            affected_bookings: number[];
            affected_requests: number[];
            occurrences: components["schemas"]["PreviewItem"][];
        };
        PublicCalendarView: {
            calendar_url: string;
            events: components["schemas"]["PublicEventView"][];
            gym: string;
            subscription_url: string;
            team: string;
            timezone: string;
            webpage_url: string;
        };
        PublicEventView: {
            activity: string;
            cancelled: boolean;
            /** Format: int64 */
            ends_at: number;
            /** Format: int64 */
            sequence: number;
            space: string;
            /** Format: int64 */
            starts_at: number;
            uid: string;
        };
        RequestCodeBody: {
            email: string;
        };
        RequestView: {
            activity: string;
            /** Format: int64 */
            id: number;
            note: string;
            reason: string;
            /** Format: int64 */
            replacement?: number | null;
            series?: string | null;
            /** Format: int64 */
            slot: number;
            status: string;
            /** Format: int64 */
            team: number;
            /** Format: int64 */
            version: number;
        };
        ResourceView: {
            /** Format: int64 */
            id: number;
            kind: string;
        };
        ScheduleView: {
            bookings: components["schemas"]["BookingView"][];
            closures: components["schemas"]["ClosureView"][];
            gym: components["schemas"]["GymView"];
            /** Format: int64 */
            now: number;
            requests: components["schemas"]["RequestView"][];
            seasons: components["schemas"]["SeasonView"][];
            slots: components["schemas"]["SlotView"][];
            swaps: components["schemas"]["SwapView"][];
            teams: components["schemas"]["TeamView"][];
        };
        /** @enum {string} */
        ScopeBody: "one" | "future" | "remaining";
        /** @enum {string} */
        SeasonState: "draft" | "active" | "closed";
        SeasonView: {
            end_date: string;
            /** Format: int64 */
            id: number;
            name: string;
            start_date: string;
            status: string;
            /** Format: int64 */
            version: number;
        };
        SessionResponse: {
            csrf_token: string;
            email: string;
            organizer: boolean;
            /** Format: int64 */
            user_id: number;
        };
        SlotView: {
            available: boolean;
            date: string;
            enabled: boolean;
            end: string;
            /** Format: int64 */
            ends_at: number;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            season: number;
            space: string;
            start: string;
            /** Format: int64 */
            starts_at: number;
            /** Format: int64 */
            version: number;
        };
        /** @enum {string} */
        SpaceBody: "full" | "half_a" | "half_b";
        StatusBody: {
            enabled: boolean;
        };
        SwapView: {
            /** Format: int64 */
            deadline: number;
            /** Format: int64 */
            first: number;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            proposer: number;
            /** Format: int64 */
            second: number;
            status: string;
            /** Format: int64 */
            version: number;
        };
        TeamView: {
            assistants: number[];
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            primary: number;
            seasons: number[];
            share_token?: string | null;
            /** Format: int64 */
            version: number;
        };
        VerifyCodeBody: {
            code: string;
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"][];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusBody"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    audit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditView"][];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    request_code: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCodeBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeResponse"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    verify_code: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    inbox: {
        parameters: {
            query?: {
                failed_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoticeView"][];
                };
            };
        };
    };
    readPublicCalendar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicCalendarView"];
                };
            };
        };
    };
    readSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleView"];
                };
            };
        };
    };
    mutate: {
        parameters: {
            query?: never;
            header: {
                /** @description 64 lowercase hex characters; reuse only for the same action */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeView"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewView"];
                };
            };
        };
    };
    feed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/calendar": string;
                };
            };
        };
    };
    live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
